### ISSUE TITLE
اشتباه نوشتاری

### ISSUE THREAD

**Issue by Galaxy-sc** [soheilsec/Interview#2]
درود
[سوال 18](https://github.com/soheilsec/WAP-Interview?tab=readme-ov-file#18-%D8%AD%D9%85%D9%84%D9%87-xee-%DA%86%DB%8C%D8%B3%D8%AA-%DA%86%DA%AF%D9%88%D9%86%D9%87-%D9%85%DB%8C-%D8%AA%D9%88%D8%A7%D9%86-%D8%AC%D9%84%D9%88%DA%AF%DB%8C%D8%B1%DB%8C-%DA%A9%D8%B1%D8%AF) به اشتباه نوشته شده XEE

**Comment by soheilsec** [comment]
سلام خیلی ممنون بابت دقت شما
